<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Materials;


class MaterialSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $materials = [
            [
                'material_number' => 'B751-010030',
                'description' => 'BOLT HEXAGONAL SOCKET TA-BA-10X30',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 40,
                'stock_maximum' => 99,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B751-010040',
                'description' => 'BOLT HEXAGONAL SOCKET TA-BA-10X40',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 40,
                'stock_maximum' => 99,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B751-010050',
                'description' => 'BOLT HEXAGONAL SOCKET TA-BA-10X50',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 20,
                'stock_maximum' => 59,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B751-012110',
                'description' => 'BOLT HEXAGONAL SOCKET TA-BA-12X110',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 4,
                'stock_maximum' => 11,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-525112',
                'description' => 'DUMB NUT FOR PADDLE F/ MIX UNIT',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 2,
                'stock_maximum' => 9,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-525113',
                'description' => 'PADDLE F/ MIX UNIT WMV-20 WMM30-00-113',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 4,
                'stock_maximum' => 13,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B027-200090',
                'description' => 'TAPE LOT NUMBERING 9 MM DYMO',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 20,
                'stock_maximum' => 49,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B720-643023',
                'description' => 'VALVE BLOW PBV-NT (Y9678-20030) IDAKA',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 10,
                'stock_maximum' => 29,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B739-110500',
                'description' => 'CABLE SCHUN 50 SQ',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 20,
                'stock_maximum' => 49,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B739-291910',
                'description' => 'GLASS TUBE S-GST-10',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 2,
                'stock_maximum' => 5,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B743-151316',
                'description' => 'THERMOCOUPLE K1000X300XD8MM SUS(cable3m)',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B743-900108',
                'description' => 'THERMO ELECTRIC TB-20-EJ8 SUS CHUBB',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 8,
                'stock_maximum' => 19,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B751-204012',
                'description' => 'BOLT & NUT HEXAGONAL HEAD TA-A-4X12',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 20,
                'stock_maximum' => 59,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B751-205030',
                'description' => 'BOLT & NUT HEXAGONAL HEAD TA-A-5X30',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 20,
                'stock_maximum' => 59,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B751-208035',
                'description' => 'BOLT & NUT HEXAGONAL HEAD TA-A-8X35',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 40,
                'stock_maximum' => 99,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B751-224080',
                'description' => 'BOLT & NUT HEXAGONAL HEAD TA-A-24X80',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 10,
                'stock_maximum' => 29,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B751-224100',
                'description' => 'BOLT & NUT HEXAGONAL HEAD TA-A-24X100',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 4,
                'stock_maximum' => 11,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B764-680020',
                'description' => 'PACKING LINK RIGHT 1 1/4" BANDO',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 4,
                'stock_maximum' => 11,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-591600',
                'description' => 'PLAGE CAP Y7971-31107',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 11,
                'stock_maximum' => 23,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-591601',
                'description' => 'HOLDER CAP R-TYPE Y7971-30892',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 11,
                'stock_maximum' => 23,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B021-211024',
                'description' => 'PAPER FILTER 567-40-02-24',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B037-051100',
                'description' => 'QUARTZ WOOL HORIBA 9052-0003',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 40,
                'stock_maximum' => 84,
                'unit_of_measure' => 'OZ',
            ],
            [
                'material_number' => 'B065-104005',
                'description' => 'CONICAL FLASK PYREX 250 ml GERMANY',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 2,
                'stock_maximum' => 5,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B065-106040',
                'description' => 'BEAKER GLASS 400 CC PYREX',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B065-202200',
                'description' => 'PLATE PORSELEN (BIG)',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B065-203200',
                'description' => 'BOWL PORCELEN 696-30-04-04 (SizeB1,30ml)',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 5,
                'stock_maximum' => 13,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B065-211000',
                'description' => 'SAMPLE PLATE   211-74539-03   SHIMADZU',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B065-304100',
                'description' => 'ROUT GLASS',
                'pic_name' => 'ZAENAL',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B923-003012',
                'description' => 'ROTARY CUTTER ED 12 SOMTA',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 4,
                'stock_maximum' => 9,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B931-071008',
                'description' => 'DIR DRILL 8MM JORAN',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 4,
                'stock_maximum' => 13,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B931-071010',
                'description' => 'DIE DRILL 10 MM JORAN',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 4,
                'stock_maximum' => 13,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B931-071012',
                'description' => 'DIE DRILL 12X160M JORAN',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 4,
                'stock_maximum' => 13,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B931-420250',
                'description' => 'DRILL MOULDING 25 X 328.5 STAR M',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 24,
                'stock_maximum' => 71,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B933-990250',
                'description' => 'DRILL FOR TIGHT PLUG',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 40,
                'stock_maximum' => 95,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B933-990252',
                'description' => 'DRILL FOR TIGHT PLUG TR-20 OHS',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 6,
                'stock_maximum' => 14,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B933-999999',
                'description' => 'DRILL FOR POURING BATH',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 4,
                'stock_maximum' => 8,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B024-401000',
                'description' => 'GRINDER STONE 4" (100X6X16) RESIBON',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 157,
                'stock_maximum' => 353,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B024-401750',
                'description' => 'GRINDING STONE 7" RESIBON',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 25,
                'stock_maximum' => 74,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B743-151812',
                'description' => 'MULTI STIK POSITHERN TC',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 800,
                'stock_maximum' => 1799,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-501200',
                'description' => 'LINNING FORMER JYOBOSYO',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 1,
                'stock_maximum' => 1,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-501201',
                'description' => 'LINING FORMER DIE PRESS',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 1,
                'stock_maximum' => 1,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-501207',
                'description' => 'FORMER FURNACE MF 750X1290',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 2,
                'stock_maximum' => 3,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-561642',
                'description' => 'COVER LADLE KALTEK L200 TYPE 80/4 FOSECO',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 2,
                'stock_maximum' => 3,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B950-510121',
                'description' => 'GRINDING WHEEL GMO-12A MITSUI',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 101,
                'stock_maximum' => 240,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B950-510270',
                'description' => 'GRINDER STONE GMO-27',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 16,
                'stock_maximum' => 35,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B950-510371',
                'description' => 'GRINDER STONE GMO-37 A MITSUI',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 16,
                'stock_maximum' => 35,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B950-510372',
                'description' => 'GRINDER STONE GMO-37 B MITSUI',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 25,
                'stock_maximum' => 69,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B879-050801',
                'description' => 'TUNGSTEN POWDER HORIBA',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 10,
                'stock_maximum' => 21,
                'unit_of_measure' => 'CAN',
            ],
            [
                'material_number' => 'B879-058501',
                'description' => 'SILICON GREASE  HIVAC-6   017-30813-01',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'TUB',
            ],
            [
                'material_number' => 'B879-064101',
                'description' => 'CURTRIDGE CPC-S YAMATO',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B889-030540',
                'description' => 'CHEMICAL METRIC 22409-32 NACALAI TEST',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 3,
                'stock_maximum' => 6,
                'unit_of_measure' => 'L',
            ],
            [
                'material_number' => 'B889-130507',
                'description' => 'MATRIC MGCL 04  24-48 MESH (500GR) HORIB',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B951-801005',
                'description' => 'GRINDER STONE HGPL-1005',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 3,
                'stock_maximum' => 6,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B951-817510',
                'description' => 'GRINDER STONE MWL CBN75#100(STANDARD)',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B862-533002',
                'description' => 'GAS CO2 (TABUNG)',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 2,
                'stock_maximum' => 5,
                'unit_of_measure' => 'TUB',
            ],
            [
                'material_number' => 'B862-560601',
                'description' => 'GAS OXIGEN O2 (6M3)',
                'pic_name' => 'ANWAR',
                'stock_minimum' => 5,
                'stock_maximum' => 10,
                'unit_of_measure' => 'TUB',
            ],
            [
                'material_number' => 'B950-600441',
                'description' => 'GRINDER STONE  100X6X16 (GREEN Z) NRS',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 100,
                'stock_maximum' => 239,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B951-070038',
                'description' => 'GRINDER STONE GSP-38',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 4,
                'stock_maximum' => 9,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B951-120002',
                'description' => 'GRINDER STONE 510x125x380 A5T3C16T5B33(N',
                'pic_name' => 'RACHMAT',

                'stock_minimum' => 4,
                'stock_maximum' => 8,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B951-961020',
                'description' => 'RUBBIN DAIWA NO. 120-10X20',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 30,
                'stock_maximum' => 69,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B953-010366',
                'description' => 'GRINDING WHEEL A36 P50X4X9.53 RESS GROW',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 40,
                'stock_maximum' => 199,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B964-110001',
                'description' => 'CLAMP STEEL RUNNER BLOCK',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B967-600420',
                'description' => 'GRINDER DISC LIGHT-TYPE USG-4-S URYU',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B967-600802',
                'description' => 'GRINDER DISC SL-2600L 180 SHINANO',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B967-632542',
                'description' => 'SANDER ORBITAL UP-25-DB URYU',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B967-656130',
                'description' => 'AIR TOOLS UD-60S-29 (923-072-0) URYU',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B967-680020',
                'description' => 'HAMMER AIR AA/0B TOKU',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B968-160801',
                'description' => 'GUN SPRAY S-710 700CC W/TANK  STAR',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B968-511065',
                'description' => 'ENGINE CLEANER K 65 100 CM',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 2,
                'stock_maximum' => 2,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B968-512800',
                'description' => 'ENGINE CLEANER EC-3B IWATA',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 2,
                'stock_maximum' => 2,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B971-190103',
                'description' => 'FILE DIAMOND TRC GS-5-M TRUSCO',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 5,
                'stock_maximum' => 11,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B971-412007',
                'description' => 'CHISEL (MATA-PAHAT) 2007 NITTO',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B971-420111',
                'description' => 'CHISEL CRANK METAL FOR FINISHING TLIJ',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 5,
                'stock_maximum' => 15,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B971-420301',
                'description' => 'CHISEL AA-3B TOKU',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B971-420429',
                'description' => 'CHISEL FPT-1-29C',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 3,
                'stock_maximum' => 7,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B722-290615',
                'description' => 'FILTER CATRIDGE PWF-1-253089 YAMATO',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B722-410201',
                'description' => 'MEMBRANE FILTER OWG-26 YAMATO',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B743-151323',
                'description' => 'THERMOCOUPLE FOR CARBOLITE CWF11/5  SINB',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-550000',
                'description' => 'ELECTRODE  06X100-30   211-74362-01  SHI',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-550305',
                'description' => 'CRUISIBLE 696-30-10-01 (Size CO,Cap15ml)',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 10,
                'stock_maximum' => 24,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-550308',
                'description' => 'CONVEX LENS  PD7000-Q1 SHIMADZU',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 2,
                'stock_maximum' => 3,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-550311',
                'description' => 'CRUCIBLE CHECK 001 - 2006 JIEBO TECH',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 7000,
                'stock_maximum' => 14999,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-550503',
                'description' => 'TUNGSTEN ELECTRODA 211-50467-01 SHIMADZU',
                'pic_name' => 'RACHMAT',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B971-430101',
                'description' => 'CHISEL BRH-1UGV',
                'pic_name' => 'EKA S',
                'stock_minimum' => 2,
                'stock_maximum' => 5,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B971-430103',
                'description' => 'CHISEL C 3',
                'pic_name' => 'EKA S',
                'stock_minimum' => 3,
                'stock_maximum' => 6,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B971-430120',
                'description' => 'CHISEL HEXAGONAL DIA.20X600 MM URYU',
                'pic_name' => 'EKA S',
                'stock_minimum' => 3,
                'stock_maximum' => 6,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B972-201020',
                'description' => 'HAMMER ENGINEERS 202A-2 TEKIRO JPN',
                'pic_name' => 'EKA S',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B972-291004',
                'description' => 'HAMMER TESTING TH-1/4 TOP',
                'pic_name' => 'EKA S',
                'stock_minimum' => 4,
                'stock_maximum' => 9,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B972-291010',
                'description' => 'HAMMER TESTING ATH-1A(1P)',
                'pic_name' => 'EKA S',
                'stock_minimum' => 8,
                'stock_maximum' => 17,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B972-291150',
                'description' => 'HAMMER ALH 3LB',
                'pic_name' => 'EKA S',
                'stock_minimum' => 4,
                'stock_maximum' => 8,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B972-691203',
                'description' => 'WRENCH DRILL TP MOULDING 4340 30X50 GENE',
                'pic_name' => 'EKA S',
                'stock_minimum' => 3,
                'stock_maximum' => 7,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B973-440100',
                'description' => 'SAFETY HOLDER ELECTRODE CRC GYM',
                'pic_name' => 'EKA S',
                'stock_minimum' => 2,
                'stock_maximum' => 3,
                'unit_of_measure' => 'SET',
            ],
            [
                'material_number' => 'B983-990100',
                'description' => 'VISCOMETER 0-100 BC',
                'pic_name' => 'EKA S',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B987-020091',
                'description' => 'DIAL INDICATOR TM-91 TECLOCK',
                'pic_name' => 'EKA S',
                'stock_minimum' => 3,
                'stock_maximum' => 5,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B039-703100',
                'description' => 'MARKER PAINT WHITE SNOWMAN',
                'pic_name' => 'EKA S',
                'stock_minimum' => 60,
                'stock_maximum' => 149,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B039-703202',
                'description' => 'MARKER PAINT GREEN SNOWMAN',
                'pic_name' => 'EKA S',
                'stock_minimum' => 60,
                'stock_maximum' => 149,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B727-401501',
                'description' => 'SPRAY NOZZLE UNIT ST-5 RUMINA',
                'pic_name' => 'EKA S',
                'stock_minimum' => 2,
                'stock_maximum' => 5,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-550300',
                'description' => 'COPPER DIE',
                'pic_name' => 'EKA S',
                'stock_minimum' => 4,
                'stock_maximum' => 9,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B779-039669',
                'description' => 'CUP PLASMA H-669-G04B DAIHEN',
                'pic_name' => 'EKA S',
                'stock_minimum' => 15,
                'stock_maximum' => 34,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B779-050669',
                'description' => 'ELECTRODA PLASMA H-669-G11 daihen',
                'pic_name' => 'EKA S',
                'stock_minimum' => 40,
                'stock_maximum' => 99,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B779-120839',
                'description' => 'TORCH BODY FOR CTPW-1201 H-839600 OTC',
                'pic_name' => 'EKA S',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B779-128390',
                'description' => 'ELECTRODA 120A H839 M00',
                'pic_name' => 'EKA S',
                'stock_minimum' => 40,
                'stock_maximum' => 99,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-551302',
                'description' => 'MOLECULAR SIEVE 210-07003-04',
                'pic_name' => 'EKA S',
                'stock_minimum' => 2,
                'stock_maximum' => 3,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-551802',
                'description' => 'REAGEN TUBE 28DX20DX150L',
                'pic_name' => 'EKA S',
                'stock_minimum' => 2,
                'stock_maximum' => 3,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-551837',
                'description' => 'O-RING PN 3200043864 EMIA 920V2',
                'pic_name' => 'EKA S',
                'stock_minimum' => 2,
                'stock_maximum' => 5,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-551838',
                'description' => 'O-RING PN 3200044093 EMIA 920V2',
                'pic_name' => 'EKA S',
                'stock_minimum' => 2,
                'stock_maximum' => 5,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-551839',
                'description' => 'O-RING PN 3200044094 EMIA 920V2',
                'pic_name' => 'EKA S',
                'stock_minimum' => 2,
                'stock_maximum' => 5,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-551840',
                'description' => 'O-RING PN 3200044099 EMIA 920V2',
                'pic_name' => 'EKA S',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-551841',
                'description' => 'O-RING PN 3200044100 EMIA 920V2',
                'pic_name' => 'EKA S',
                'stock_minimum' => 2,
                'stock_maximum' => 5,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-551850',
                'description' => 'CRUSIBLE STAND PN 3200277779 EMIA 920V2',
                'pic_name' => 'EKA S',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B862-550350',
                'description' => 'GAS NITROGEN (3,5 M3)',
                'pic_name' => 'EKA S',
                'stock_minimum' => 5,
                'stock_maximum' => 10,
                'unit_of_measure' => 'TUB',
            ],
            [
                'material_number' => 'B862-500801',
                'description' => 'GAS ACETYLINE 8 M3',
                'pic_name' => 'EKA S',
                'stock_minimum' => 5,
                'stock_maximum' => 10,
                'unit_of_measure' => 'TUB',
            ],
            [
                'material_number' => 'B777-551851',
                'description' => 'CYL. FILTER PN 3200277780 EMIA 920V2',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-551852',
                'description' => 'DUST CATCH PN 3200277778 EMIA 920V2',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-551853',
                'description' => 'DUST PACKING PN 320044474 EMIA 920V2',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-551854',
                'description' => 'PIPE PN 3200043616 EMIA 920V2',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-551919',
                'description' => 'DUST CATCH 9052019000 HORIBA',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-559056',
                'description' => 'TUBE COMBUSTION 9052-0056-00',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B856-050000',
                'description' => 'OIL FOR VACCUM PUMP MR-200 1L MORESCO',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B862-572030',
                'description' => 'ASKARITE II ABSORBENT 20-30 MESH HORIBA',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'ROL',
            ],
            [
                'material_number' => 'B779-128392',
                'description' => 'SHIELD CUP H839-G02',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 25,
                'stock_maximum' => 64,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B779-128393',
                'description' => 'TIP 120 A H839-G03',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 100,
                'stock_maximum' => 199,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B779-205669',
                'description' => 'TORCH BODY H-669-H00 DAIHEN',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B779-908690',
                'description' => 'MARKED-H TIP H-669-G05 DAIHEN',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 130,
                'stock_maximum' => 289,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B973-340100',
                'description' => 'FLASH BACK ARRESTOR',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 2,
                'stock_maximum' => 4,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B743-151811',
                'description' => 'THERMOCOUPLE RKP-250',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 800,
                'stock_maximum' => 1799,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B777-520248',
                'description' => 'BUSH FLASK G-MFB-MJ-CR,DR,CF&DF TLI',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 8,
                'stock_maximum' => 17,
                'unit_of_measure' => 'SET',
            ],
            [
                'material_number' => 'B777-561644',
                'description' => 'COVER LADLE1/2 KALTEK L200TM 80*4 FOSECO',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 3,
                'stock_maximum' => 7,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B824-110100',
                'description' => 'PAINT PYLOX RED 101 NIPPON PAINT',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 24,
                'stock_maximum' => 59,
                'unit_of_measure' => 'TIN',
            ],
            [
                'material_number' => 'B824-110900',
                'description' => 'PAINT PYLOX BLACK 109 NIPPON PAINT',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 36,
                'stock_maximum' => 83,
                'unit_of_measure' => 'TIN',
            ],
            [
                'material_number' => 'B869-000100',
                'description' => 'MICRO CHECK NO. 1 & 3 TAIHO KOHZAI',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 24,
                'stock_maximum' => 71,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B869-000200',
                'description' => 'MICRO CHECK NO. 2 TAIHO KOZAI',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 24,
                'stock_maximum' => 71,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B869-000400',
                'description' => 'MICRO CHECK NO. 4 TAIHO KOZAI',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 24,
                'stock_maximum' => 71,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B971-410101',
                'description' => 'GARPU TERAK - SMM',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 25,
                'stock_maximum' => 50,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B971-410102',
                'description' => 'PENGAIT POURING PENDEK -SMM',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 11,
                'stock_maximum' => 30,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B971-410104',
                'description' => 'INGOT HOOK-SMM',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 60,
                'stock_maximum' => 140,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B971-410106',
                'description' => 'GAYUNG SAMPLE -SMM',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 10,
                'stock_maximum' => 21,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B971-410107',
                'description' => 'STICK  AGARI SMM',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 2,
                'stock_maximum' => 6,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B971-410127',
                'description' => 'PALU FETLING - SMM',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 4,
                'stock_maximum' => 9,
                'unit_of_measure' => 'PC',
            ],
            [
                'material_number' => 'B027-340001',
                'description' => 'TESSA 1" PERMACE (USA)',
                'pic_name' => 'FAHRI',
                'stock_minimum' => 101,
                'stock_maximum' => 251,
                'unit_of_measure' => 'PC',
            ],
        ];

        foreach ($materials as $material) {
            Materials::create($material);
        }
    }
}
